package kr.java.documind.domain.archive.etl.service;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.Map;
import java.util.Set;
import kr.java.documind.domain.archive.etl.infrastructure.DocumentTextExtractor;
import kr.java.documind.domain.archive.etl.infrastructure.EmbeddingModelClient;
import kr.java.documind.domain.archive.etl.infrastructure.EmbeddingSseManager;
import kr.java.documind.domain.archive.etl.model.enums.EmbeddingStatus;
import kr.java.documind.domain.archive.etl.model.event.EmbeddingStatusEvent;
import kr.java.documind.domain.archive.etl.repository.VectorStoreRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.ai.document.Document;
import org.springframework.ai.document.DocumentTransformer;
import org.springframework.context.ApplicationEventPublisher;
import org.springframework.stereotype.Service;

@Slf4j
@Service
@RequiredArgsConstructor
public class DocumentEtlService {

    private static final Set<String> AUTO_GENERATED_KEYS = Set.of("source", "parent_document_id");

    private final DocumentTextExtractor documentTextExtractor;
    private final DocumentTransformer documentTransformer;
    private final EmbeddingModelClient embeddingModelClient;
    private final VectorStoreRepository vectorStoreRepository;

    private final EmbeddingSseManager embeddingSseManager;
    private final ApplicationEventPublisher eventPublisher;

    public void process(Long sourceId, Path tempFilePath) {
        try {
            changeStatus(sourceId, EmbeddingStatus.PROCESSING);

            List<Document> documents = documentTextExtractor.read(tempFilePath);

            List<Document> chunks = documentTransformer.transform(documents);
            chunks.forEach(this::stripAutoGeneratedMetadata);

            if (chunks.isEmpty()) {
                log.warn("[ETL] 추출된 텍스트가 없습니다 - sourceId: {}", sourceId);
                changeStatus(sourceId, EmbeddingStatus.FAILED);
                return;
            }

            List<String> texts = chunks.stream().map(Document::getText).toList();
            List<float[]> embeddings = embeddingModelClient.embed(texts);

            vectorStoreRepository.insertChunks(sourceId, chunks, embeddings);

            changeStatus(sourceId, EmbeddingStatus.SUCCESS);
        } catch (Exception e) {
            log.error("[ETL] 벡터화 실패 - sourceId: {}", sourceId, e);
            changeStatus(sourceId, EmbeddingStatus.FAILED);
        } finally {
            deleteTempFile(tempFilePath);
        }
    }

    public void deleteVectors(Long sourceId) {
        try {
            vectorStoreRepository.deleteBySourceId(sourceId);
        } catch (Exception e) {
            log.error("[ETL] 벡터 삭제 실패 - sourceId: {}", sourceId, e);
        }
    }

    private void changeStatus(Long sourceId, EmbeddingStatus status) {
        eventPublisher.publishEvent(new EmbeddingStatusEvent(sourceId, status));
        embeddingSseManager.send(sourceId, status);
    }

    private void stripAutoGeneratedMetadata(Document chunk) {
        Map<String, Object> metadata = chunk.getMetadata();
        AUTO_GENERATED_KEYS.forEach(metadata::remove);
    }

    private void deleteTempFile(Path tempFilePath) {
        try {
            Files.deleteIfExists(tempFilePath);
        } catch (IOException e) {
            log.warn("[ETL] 임시 파일 삭제 실패: {}", tempFilePath, e);
        }
    }
}
