package kr.java.documind.domain.archive.vector.service;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.UUID;
import kr.java.documind.domain.archive.vector.infrastructure.DocumentContentExtractor;
import kr.java.documind.domain.archive.vector.infrastructure.EmbeddingModelClient;
import kr.java.documind.domain.archive.vector.infrastructure.EmbeddingStatusSseManager;
import kr.java.documind.domain.archive.vector.infrastructure.VectorStoreManager;
import kr.java.documind.domain.archive.vector.model.enums.EmbeddingStatus;
import kr.java.documind.domain.archive.vector.model.event.EmbeddingStatusEvent;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.ai.document.Document;
import org.springframework.ai.document.DocumentTransformer;
import org.springframework.context.ApplicationEventPublisher;
import org.springframework.stereotype.Service;
import org.springframework.web.servlet.mvc.method.annotation.SseEmitter;

@Slf4j
@Service
@RequiredArgsConstructor
public class EtlService {

    private static final Set<String> AUTO_GENERATED_KEYS = Set.of("source", "parent_document_id");

    private final DocumentContentExtractor documentContentExtractor;
    private final DocumentTransformer documentTransformer;
    private final EmbeddingModelClient embeddingModelClient;
    private final VectorStoreManager vectorStoreManager;

    private final ApplicationEventPublisher eventPublisher;
    private final EmbeddingStatusSseManager embeddingStatusSseManager;

    public SseEmitter subscribe(Long sourceId, EmbeddingStatus currentStatus) {
        return embeddingStatusSseManager.register(sourceId, currentStatus);
    }

    public void process(UUID projectId, Long sourceId, Path tempFilePath) {
        try {
            changeStatus(sourceId, EmbeddingStatus.PROCESSING);

            List<Document> documents = documentContentExtractor.read(tempFilePath);

            List<Document> chunks = documentTransformer.transform(documents);
            chunks.forEach(
                    chunk -> {
                        stripAutoGeneratedMetadata(chunk);
                        chunk.getMetadata().put("project_id", projectId);
                        chunk.getMetadata().put("source_id", sourceId);
                    });

            if (chunks.isEmpty()) {
                log.warn("[ETL] 추출된 텍스트가 없습니다 - sourceId: {}", sourceId);
                changeStatus(sourceId, EmbeddingStatus.FAILED);
                return;
            }

            List<String> texts = chunks.stream().map(Document::getText).toList();
            List<float[]> embeddings = embeddingModelClient.embed(texts);

            vectorStoreManager.insertChunks(sourceId, chunks, embeddings);

            changeStatus(sourceId, EmbeddingStatus.SUCCESS);
        } catch (Exception e) {
            log.error("[ETL] 벡터화 실패 - sourceId: {}", sourceId, e);
            cleanupVectors(sourceId);
            changeStatus(sourceId, EmbeddingStatus.FAILED);
        } finally {
            deleteTempFile(tempFilePath);
        }
    }

    private void changeStatus(Long sourceId, EmbeddingStatus status) {
        eventPublisher.publishEvent(new EmbeddingStatusEvent(sourceId, status));
        embeddingStatusSseManager.send(sourceId, status);
    }

    private void stripAutoGeneratedMetadata(Document chunk) {
        Map<String, Object> metadata = chunk.getMetadata();
        AUTO_GENERATED_KEYS.forEach(metadata::remove);
    }

    private void cleanupVectors(Long sourceId) {
        try {
            vectorStoreManager.deleteBySourceId(sourceId);
        } catch (Exception e) {
            log.warn("[ETL] 실패 후 벡터 정리 실패 - sourceId: {}", sourceId, e);
        }
    }

    private void deleteTempFile(Path tempFilePath) {
        try {
            Files.deleteIfExists(tempFilePath);
        } catch (IOException e) {
            log.warn("[ETL] 임시 파일 삭제 실패: {}", tempFilePath, e);
        }
    }
}
